---

- hosts: cisco
  gather_facts: no

  tasks:
   - name: crawl config file
     local_action:
       module: ios_command
       authorize: yes
       auth_pass: "{{ enable_pass }}"
       username: "{{ ansible_ssh_user }}"
       password: "{{ ansible_ssh_pass }}"
       host: "{{ inventory_hostname }}"
       commands:
         - show run
     register: result
     vars:
      ansible_persistent_log_messages: True

   - name: log write out
     local_action:
      module: template
      src: conf.j2
      dest: "{{ config_path }}/{{ inventory_hostname }}.log"

   - name: parse config
     local_action: shell cat {{ config_path }}/{{ inventory_hostname }}.log | sed -e 's/        \"//g' | sed -e 's/",//g' | sed -e 's/"//g' | sed -e "1,2d" | sed -e '$d' | sed -e '$d' > {{ config_path }}/{{ inventory_hostname }}.conf

   - name: remove logfile
     local_action: file path={{ config_path }}/{{ inventory_hostname }}.log state=absent
